#!/usr/bin/env python3
"""
Ingest real historical wildfire records from authoritative services.

Current source:
- USGS/NIFC Historic Wildfires >=100 acres (ArcGIS MapServer)
  https://mercator.env.nm.gov/server/rest/services/nifc/historic_wildfires/MapServer
- NASA FIRMS active fire detections (optional, requires MAP_KEY)
  https://firms.modaps.eosdis.nasa.gov/api/

Writes:
- docs/data/historical_fires.geojson (point features for map exploration)

No synthetic data is generated by this script.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import time
import urllib.parse
import urllib.request
from datetime import date, datetime, timedelta
from pathlib import Path


MAPSERVER_BASE = "https://mercator.env.nm.gov/server/rest/services/nifc/historic_wildfires/MapServer"
FIRMS_AREA_API_BASE = "https://firms.modaps.eosdis.nasa.gov/api/area/csv"
OUT_GEOJSON = Path("docs/data/historical_fires.geojson")

# Default study area (NW Iowa + SE South Dakota context)
DEFAULT_BBOX = (-97.60, 41.80, -94.90, 43.85)  # min_lon, min_lat, max_lon, max_lat

FIRMS_SOURCE_START = {
    "MODIS_SP": date(2000, 11, 1),
    "MODIS_NRT": date(2000, 11, 1),
    "VIIRS_SNPP_SP": date(2012, 1, 20),
    "VIIRS_SNPP_NRT": date(2012, 1, 20),
    "VIIRS_NOAA20_SP": date(2018, 4, 1),
    "VIIRS_NOAA20_NRT": date(2018, 4, 1),
    "VIIRS_NOAA21_NRT": date(2024, 1, 17),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Ingest historical wildfire records.")
    parser.add_argument("--start-year", type=int, default=2004, help="First year to ingest.")
    parser.add_argument("--end-year", type=int, default=2023, help="Last year to ingest.")
    parser.add_argument(
        "--bbox",
        type=float,
        nargs=4,
        metavar=("MIN_LON", "MIN_LAT", "MAX_LON", "MAX_LAT"),
        default=DEFAULT_BBOX,
        help="Bounding box in WGS84 coordinates.",
    )
    parser.add_argument(
        "--min-acres",
        type=float,
        default=0.0,
        help="Optional additional area filter in acres (0 uses source threshold only).",
    )
    parser.add_argument(
        "--include-firms",
        action="store_true",
        help="Include NASA FIRMS active fire detections (requires --firms-map-key).",
    )
    parser.add_argument(
        "--firms-map-key",
        default="",
        help="NASA FIRMS MAP_KEY (required when --include-firms is used).",
    )
    parser.add_argument(
        "--firms-sources",
        default="MODIS_SP,VIIRS_SNPP_SP,VIIRS_NOAA20_SP",
        help="Comma-separated FIRMS sources. Example: MODIS_SP,VIIRS_SNPP_SP",
    )
    return parser.parse_args()


def fetch_json(url: str, retries: int = 4) -> dict:
    request = urllib.request.Request(url, headers={"User-Agent": "burnable-breadbasket/ingest"})
    last_err = None
    for i in range(retries):
        try:
            with urllib.request.urlopen(request, timeout=60) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except Exception as err:  # noqa: BLE001
            last_err = err
            time.sleep(min(10.0, (2**i) + 0.3))
    raise RuntimeError(f"Failed request after retries: {last_err}")


def fetch_text(url: str, retries: int = 4) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "burnable-breadbasket/ingest"})
    last_err = None
    for i in range(retries):
        try:
            with urllib.request.urlopen(request, timeout=60) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except Exception as err:  # noqa: BLE001
            last_err = err
            time.sleep(min(10.0, (2**i) + 0.3))
    raise RuntimeError(f"Failed request after retries: {last_err}")


def get_layer_ids_by_year() -> dict[int, int]:
    url = f"{MAPSERVER_BASE}?f=pjson"
    data = fetch_json(url)
    out = {}
    for lyr in data.get("layers", []):
        name = str(lyr.get("name", ""))
        if name.isdigit():
            out[int(name)] = int(lyr["id"])
    return out


def centroid_from_polygon_geometry(geom: dict) -> tuple[float, float]:
    # ArcGIS geojson features here are Polygon/MultiPolygon in WGS84 after outSR=4326.
    if geom["type"] == "Polygon":
        rings = geom["coordinates"]
        points = rings[0]
    elif geom["type"] == "MultiPolygon":
        points = geom["coordinates"][0][0]
    else:
        raise ValueError(f"Unsupported geometry type: {geom['type']}")

    sx = 0.0
    sy = 0.0
    n = 0
    for p in points:
        sx += float(p[0])
        sy += float(p[1])
        n += 1
    if n == 0:
        raise ValueError("Empty polygon coordinate list")
    return sx / n, sy / n


def query_year_layer(layer_id: int, bbox: tuple[float, float, float, float], min_acres: float) -> list[dict]:
    min_lon, min_lat, max_lon, max_lat = bbox
    where = "1=1" if min_acres <= 0 else f"acres >= {float(min_acres)}"
    query = {
        "f": "geojson",
        "where": where,
        "outFields": "name,year,acres",
        "returnGeometry": "true",
        "geometryType": "esriGeometryEnvelope",
        "geometry": f"{min_lon},{min_lat},{max_lon},{max_lat}",
        "inSR": "4326",
        "outSR": "4326",
        "spatialRel": "esriSpatialRelIntersects",
    }
    url = f"{MAPSERVER_BASE}/{layer_id}/query?{urllib.parse.urlencode(query)}"
    data = fetch_json(url)
    return data.get("features", [])


def feature_to_point_record(feature: dict, seq: int) -> dict:
    props = feature.get("properties", {})
    geom = feature.get("geometry", {})
    lon, lat = centroid_from_polygon_geometry(geom)

    event_id = f"nifc_{props.get('year', 'unknown')}_{seq:06d}"
    return {
        "type": "Feature",
        "properties": {
            "event_id": event_id,
            "date": None,
            "county": None,
            "state": None,
            "incident_name": props.get("name"),
            "year": props.get("year"),
            "acres": props.get("acres"),
            "source": "USGS/NIFC Historic Wildfires >=100 acres",
            "source_url": MAPSERVER_BASE,
            "source_layer_type": "yearly_perimeter_layer",
            "source_note": "Point = perimeter centroid for exploration; original record is polygon perimeter.",
        },
        "geometry": {
            "type": "Point",
            "coordinates": [round(float(lon), 6), round(float(lat), 6)],
        },
    }


def daterange_windows(start_dt: date, end_dt: date, days: int = 5) -> list[tuple[date, int]]:
    out = []
    cur = start_dt
    while cur <= end_dt:
        span = min(days, (end_dt - cur).days + 1)
        out.append((cur, span))
        cur = cur + timedelta(days=span)
    return out


def parse_float_or_none(value: str | None) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def parse_date_or_none(value: str | None) -> str | None:
    if not value:
        return None
    for fmt in ("%Y-%m-%d", "%Y-%m-%d %H:%M:%S"):
        try:
            return datetime.strptime(value, fmt).date().isoformat()
        except ValueError:
            continue
    return value[:10]


def fetch_firms_rows(
    map_key: str,
    source: str,
    bbox: tuple[float, float, float, float],
    start_year: int,
    end_year: int,
) -> list[dict]:
    min_lon, min_lat, max_lon, max_lat = bbox
    area = f"{min_lon},{min_lat},{max_lon},{max_lat}"
    start_dt = date(start_year, 1, 1)
    end_dt = date(end_year, 12, 31)
    source_min = FIRMS_SOURCE_START.get(source)
    if source_min is not None and start_dt < source_min:
        start_dt = source_min
    if start_dt > end_dt:
        return []

    rows = []
    for window_start, span in daterange_windows(start_dt, end_dt, days=5):
        url = f"{FIRMS_AREA_API_BASE}/{map_key}/{source}/{area}/{span}/{window_start.isoformat()}"
        try:
            text = fetch_text(url)
        except RuntimeError as err:
            # Keep ingest robust across occasional product/date API errors.
            print(f"Warning: skipping FIRMS window {source} {window_start} +{span - 1}d: {err}")
            continue
        reader = csv.DictReader(text.splitlines())
        for row in reader:
            rows.append(row)
        time.sleep(0.12)
    return rows


def firms_row_to_feature(row: dict, source: str, seq: int) -> dict | None:
    lat = parse_float_or_none(row.get("latitude"))
    lon = parse_float_or_none(row.get("longitude"))
    if lat is None or lon is None:
        return None

    acq_date = parse_date_or_none(row.get("acq_date"))
    year_val = None
    if acq_date:
        try:
            year_val = int(acq_date[:4])
        except ValueError:
            pass

    event_id = f"firms_{source.lower()}_{seq:08d}"
    return {
        "type": "Feature",
        "properties": {
            "event_id": event_id,
            "date": acq_date,
            "county": None,
            "state": None,
            "incident_name": None,
            "year": year_val,
            "acres": None,
            "source": f"NASA FIRMS {source}",
            "source_url": "https://firms.modaps.eosdis.nasa.gov/api/",
            "source_layer_type": "satellite_active_fire_detection",
            "source_note": "Point is a satellite active-fire detection, not final perimeter.",
            "satellite": row.get("satellite"),
            "instrument": row.get("instrument"),
            "confidence": row.get("confidence"),
            "frp": parse_float_or_none(row.get("frp")),
            "brightness": parse_float_or_none(row.get("brightness")),
            "daynight": row.get("daynight"),
            "firms_source_product": source,
        },
        "geometry": {"type": "Point", "coordinates": [round(lon, 6), round(lat, 6)]},
    }


def main() -> None:
    args = parse_args()
    bbox = tuple(args.bbox)
    layer_ids = get_layer_ids_by_year()

    features: list[dict] = []
    seq = 0
    for year in range(args.start_year, args.end_year + 1):
        layer_id = layer_ids.get(year)
        if layer_id is None:
            continue
        year_features = query_year_layer(layer_id, bbox, args.min_acres)
        for feat in year_features:
            seq += 1
            features.append(feature_to_point_record(feat, seq))

    source_details = [
        {
            "name": "USGS/NIFC Historic Wildfires >=100 acres",
            "type": "perimeter_centroid_point",
            "url": MAPSERVER_BASE,
        }
    ]

    if args.include_firms:
        key = (args.firms_map_key or os.environ.get("FIRMS_MAP_KEY", "")).strip()
        if not key:
            raise ValueError("--include-firms requires --firms-map-key or FIRMS_MAP_KEY env var")
        if key.upper() in {"YOUR_FIRMS_MAP_KEY", "MAP_KEY", "API_KEY"}:
            raise ValueError(
                "FIRMS map key looks like a placeholder. Replace with a real MAP_KEY from "
                "https://firms.modaps.eosdis.nasa.gov/api/map_key/"
            )
        firms_sources = [s.strip() for s in args.firms_sources.split(",") if s.strip()]
        seq_firms = 0
        for source in firms_sources:
            firms_rows = fetch_firms_rows(key, source, bbox, args.start_year, args.end_year)
            for row in firms_rows:
                seq_firms += 1
                feat = firms_row_to_feature(row, source, seq_firms)
                if feat is not None:
                    features.append(feat)
            source_details.append(
                {
                    "name": f"NASA FIRMS {source}",
                    "type": "active_fire_detection_point",
                    "url": "https://firms.modaps.eosdis.nasa.gov/api/",
                }
            )

    out = {
        "type": "FeatureCollection",
        "name": "historical_fires_real",
        "features": features,
        "meta": {
            "sources": source_details,
            "year_range": [args.start_year, args.end_year],
            "bbox_wgs84": list(bbox),
            "min_acres_filter": args.min_acres,
            "include_firms": bool(args.include_firms),
            "record_count": len(features),
            "synthetic_data": False,
        },
    }
    OUT_GEOJSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_GEOJSON.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Wrote {OUT_GEOJSON} with {len(features)} records")


if __name__ == "__main__":
    main()
